[package]
name = "cqrs-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
cqrs-es = "0.4.2"
async-trait = "0.1.68"
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
